name: ping_discover_network
description: Library that allows to ping IP subnet and discover network devices. Could be used to find printers and other devices and services in a local network.
version: 0.2.0+1
homepage: https://github.com/andrey-ushakov/ping_discover_network
publish_to: none

environment:
  sdk: ">=2.17.0-85.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
